version: "3.7"
  services:
    database:
      image: postgres:13-alpine
      container_name: tt_database_container
      restart: always
      user: postgres
      environment:
       - POSTGRES_USER: ${DB_USER}
       - POSTGRES_PASSWORD: ${DB_PASSWORD}
       - POSTGRES_DB: ${DB_NAME}
       - DATABASE_HOST: ${DB_HOST}
      volumes:
        - postgres_volume:/var/lib/postgresql/data
      networks:
        default:
          ipv4_address: '144.16.0.64'
          
    pgadmin:
      image: dpage/pgadmin4:6.2
      container_name: tt_pgadmin_container
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - '${PGADMIN_PORT}:80'
      depends_on:
        - database
      volumes:
        - pg_admin_volume:/var/lib/pgadmin
        
    web_client:
      image: localhost:5000/web-client:latest
      container_name: tt_web_client_container
      restart: always
      build:
        dockerfile: ./Dockerfile
      context: ../web_client
      env_file:
        - .env
      ports:
        8080:12001
    
    mobile:
      image: localhost:5000/mobile:latest
      container_name: tt_mobile_container
      restart: always
      build:
        dockerfile: ./Dockerfile
      context: ../mobile
      env_file:
        - .env
      ports:
        8080:12002
        
    server:
      image: localhost:5000/server:latest
      container_name: tt_server_container
      restart: always
      build:
        dockerfile: ./Dockerfile
      context: ../server
      env_file:
        - .env
      ports:
        8080:12003, 12004
        
  volumes:
    postgres_volume:
      name: 'postgres_volume_001'
    pg_admin_volume:
      name: 'pg_admin_volume_001'
