name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        working-directory: web-client
    - name: Build Web-client
      run: | 
        cd web-client
        npm install
    - name: Test Web-client
      run: |
        cd webclient
        npm run test
